# This is a basic workflow to help you get started with Actions

name: Sync

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Set up SSH key
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          rm -rf ~/.ssh/id_ed25519
          echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

      - name: Configure git
        run: |
          git config --global user.name "Guangxu Li"
          git config --global user.email "guangxu.li@nyu.edu"

      - name: Prepare release branch
        run: |
          git checkout -b tmp

          rm -rf assets/*.pdf
          rm -rf assets/*.epub
          rm -rf .github
          rm -rf netlify.toml

          git add .
          git commit --amend --no-edit
          git remote add release_repo git@github.com:guangxu-li/guangxuli-wiki.git 
          git push -f -u release_repo tmp:main

      - name: Clean up
        run: |
          rm -rf ~/.ssh
